services:
  db:
    image: my_mysql
    env_file:
      - .env
    container_name: my_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - flexnet

  backend:
    build:
      dockerfile: Dockerfile

    image: flex_translator
    container_name: flask_app
    depends_on:
      - db
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - flexnet

volumes:
  mysqldata:

networks:
  flexnet:
    driver: bridge
